gallery_model_path: checkpoints/cifar100_old.pt
query_model_path: checkpoints/cifar100_old.pt

eval_params:
  distance_metric_name: l2
  verbose: True
  compute_map: True

dataset_params: # Test split of the dataset will be used as both gallery and query sets.
  name: cifar100
  data_root: data_store/cifar-100-python
  num_workers: 20
  batch_size: 1024
