gallery_model_path: checkpoints/imagenet_old.pt
query_model_path: checkpoints/imagenet_old.pt

eval_params:
  distance_metric_name: l2
  verbose: True
  compute_map: True

dataset_params: # Test split of the dataset will be used as both gallery and query sets.
  name: imagenet
  data_root: data_store/imagenet-1.0.2/data/raw
  num_workers: 20
  batch_size: 1024
